name: Python package

on:
#  push:
  release:
    types:
      - published

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      run: |
        cd Bindings/Python
        pip install -r requirements.txt
        python copy-cpp-files.py
        python -m build
        pip install --find-links=./dist doxapy
    - name: Run tests
      run: |
        cd Bindings/Python
        python test/test_doxa.py
    - name: Upload SDist
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: sdist-${{ github.run_id }}
        path: Bindings/Python/dist/*.tar.gz
    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-${{ github.run_id }}
        path: Bindings/Python/dist/*.whl

  upload-pypi:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Display Artifacts
        run: ls -R dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
